[package]
name = "compress-dir-as-gz"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flate2 = { version = "1.0.25", features = ["zlib-ng"], default-features = false }
tar = "0.4.38"
