[package]
name = "read-config-file"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
config = { version = "0.13.1", features = ["toml"] }
serde = { version = "1.0", features = ["derive"] }

